image: node:10.16.3

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_SHA"
  policy: pull
  paths:
    - node_modules/
    - dist

build:
  stage: build
  script:
    - npm install && npm run build
  except:
    - /^release_/
  cache:
    key: "$CI_COMMIT_SHA"
    policy: push
    paths:
      - node_modules/
      - dist

test:
  stage: test
  dependencies:
    - build
  script:
    - npm test -- --forceExit

lint:
  stage: test
  dependencies:
    - build
  script:
    - npm run lint
