name: Build

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.1]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run eslint
